import { exec } from 'child_process';
import consola from 'consola';
import { DataSource } from 'typeorm';
import { promisify } from 'util';

const execAsync = promisify(exec);

export async function generateMigrations(dataSource: DataSource): Promise<void> {
  try {
    const migrationName = `AutoGeneratedMigration-${Date.now()}`;
    const command = `npm run typeorm -- migration:generate src/database/migrations/${migrationName}`;

    consola.start(`Running migration generation command: ${command}`);

    const { stdout, stderr } = await execAsync(command);

    if (stderr) throw new Error(stderr);

    consola.success(`Migration generated successfully:\n${stdout}`);
  } catch (error) {
    consola.error('Error generating migrations:', error);
    throw error; 
  }
}

export async function runMigrations(dataSource: DataSource): Promise<void> {
  try {
    const command = `npm run migration:run`;

    consola.start(`Running migration run command: ${command}`);

    const { stdout, stderr } = await execAsync(command);

    if (stderr) throw new Error(stderr);

    consola.success(`Migration run successfully:\n${stdout}`);
  } catch (error) {
    consola.error('Error run migrations:', error);
    throw error; 
  }
}
