import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration17317516415771731751642012 implements MigrationInterface {
    name = 'AutoGeneratedMigration17317516415771731751642012'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "product" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "code" character varying(25) NOT NULL, "name" character varying(100) NOT NULL, "isFreeze" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "product"`);
    }

}
