version: '3'

services:
  ROZY-AUTH:
    container_name: rozy_auth
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      TZ: Asia/Saigon
    ports:
      - 6000:4600
    networks:
      - local

networks:
  local:
    external: true
